version: '3.8'

services:

  nestjs-app:
    build:
      context: ./
      dockerfile: ./apps/auth/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - path: ./apps/auth/.env
        required: true 

  angular-app:
    build:
      context: ./
      dockerfile: ./apps/client-auth/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - nestjs-app
